### ISSUE TITLE
Texturi zar

### ISSUE THREAD

**Issue by ghost** [marianspoiala/RollEm#16]
- texturi pentru fiecare literă a alfabetului ce poate apărea pe zar
- dimensiune 256x256
- de preferat format lossless (ex PNG)

**Comment by mariaig** [comment]
#12

**Comment by mariaig** [comment]
cel mai probabil vom schimba texturile de pe zaruri dupa ce vom avea ceva functional. eu am facut fetele pt fiecare zar insa trebuie sa vedem mai exact cum le vom asocia:)... cod vs imagine

**Comment by mariaig** [comment]
texturile pt zaruri pot fi gasite pe drive (https://drive.google.com/drive/folders/0B_y5RIclGIIJRWlDMGFZYUc2UlE)
