### ISSUE TITLE
Detectie fata zar

### ISSUE THREAD

**Issue by alexandrugavril** [marianspoiala/RollEm#17]
Trebuie sa putem detecta coliziunea zarului cu tabla pentru identificarea literelor ce au cazut. In momentul in care viteza zarurilor este 0, atunci se va calcula litera care a cazut. In cazul in care a cazut zarul intr-o parte se va arunca din nou zarul respectiv.
De asemenea odata calculate vor fi trimise catre modulul urmator.

**Comment by mariaig** [comment]
see #15
