### ISSUE TITLE
cronometru

### ISSUE THREAD

**Issue by mariaig** [marianspoiala/RollEm#7]
sistem pt afisare a timpului ramas pt a completa cuvintele

**Comment by marianspoiala** [comment]
Din cauza ca nu exista obiectul master care sa le coordoneze pe celalalte, cronometrul porneste pt fiecare obiect in parte si nu funcitoneaza corect. Am deschis un issue pt asta.

**Comment by florin-avram** [comment]
Cred ca puteti atasa cronometrul de scena. Sau sa instantiati cronometrul
dintr-un script atasat temei.

În data de 11 noiembrie 2015, 10:12, marianspoiala <notifications@github.com
